name: Build and Test Lazy Monkey

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Updated to .NET 9

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --output ./out

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal

      - name: ZIP Application
        run: |
          zip -r ./LazyMonkey.zip ./out/*

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy Bicep template
        run: az deployment group create -g LazyMonkey --template-file ./templates/template.bicep --parameters appServiceName=${{vars.LAZY_MONKEY_WEBAPP_NAME}}

      - name: Deploy Application
        run: |
          az webapp deploy --resource-group LazyMonkey --name ${{vars.LAZY_MONKEY_WEBAPP_NAME}} --src-path ./LazyMonkey.zip --type zip